name: test

on:
  push:
    branches:
      - main

jobs:
  gotest:
    runs-on: ubuntu-latest

    steps: 
      - name: test service
        run: echo "Testing service..."
      - name: sleep
        run: sleep 100